apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-config
  template:
    metadata:
      labels:
        app: spring-config
    spec:
      containers:
        - name: spring-config
          image: choissu/ficket:springconfig-latest
          ports:
            - containerPort: 8888
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"